query getLeases {
  goodses(query: { type: 1 }, first: 0) {
    _id
    imgSrc
    name
    discription
    price
    priceUnit {
      type
      displayName
    }
    priceOld
    sales
    mark
    details
  }
}
